export const ROUTE_LIST = {
  ai: '/',
  coach: '/coach',
  error: '/error',
};

export const CHECK_MY_WRITING_OPTIONS = {
  purpose: ['General', 'Academic', 'Business', 'Creative', 'Diary', 'Email', 'Formal Statements', 'School Application'],
  style: [
    'General',
    'Academic',
    'Analytical',
    'Argumentative',
    'Conversational',
    'Creative',
    'Critical',
    'Descriptive',
    'Epigrammatic',
    'Expository',
    'Instructive',
    'Journalistic',
    'Metaphorical',
    'Narrative',
    'Objective',
    'Satirical',
    'Subjective',
    'Technical',
  ],
  tone: [
    'General',
    'Advocatory',
    'Assertive',
    'Cold',
    'Confident',
    'Cynical',
    'Emotional',
    'Empathetic',
    'Formal',
    'Friendly',
    'Informal',
    'Ironic',
    'Optimistic',
    'Pessimistic',
    'Playful',
    'Sarcastic',
    'Satiric',
    'Sympathetic',
  ],
};
