export const ROUTE_LIST = {
  ai: '/ai',
  coach: '/coach',
  error: '/error',
  dashboard: '/dashboard',
};

export const CHECK_MY_WRITING_OPTIONS = {
  Purpose: ['General', 'Academic', 'Business', 'Creative', 'Diary', 'Email', 'Formal Statements', 'School Application'],
  Style: [
    'General',
    'Academic',
    'Analytical',
    'Argumentative',
    'Conversational',
    'Creative',
    'Critical',
    'Descriptive',
    'Epigrammatic',
    'Expository',
    'Instructive',
    'Journalistic',
    'Metaphorical',
    'Narrative',
    'Objective',
    'Satirical',
    'Subjective',
    'Technical',
  ],
  Tone: [
    'General',
    'Advocatory',
    'Assertive',
    'Cold',
    'Confident',
    'Cynical',
    'Emotional',
    'Empathetic',
    'Formal',
    'Friendly',
    'Informal',
    'Ironic',
    'Optimistic',
    'Pessimistic',
    'Playful',
    'Sarcastic',
    'Satiric',
    'Sympathetic',
  ],
};

export const META_DATA = {
  title: 'Altrid | Create the writing you want',
  description: 'Create the writing you want',
  url: 'https://www.altridai.com',
  image: '/og-image.png',
  userName: 'Optmier',
};
