name: Open release branch

on:
  workflow_dispatch:

env:
  TIMEZONE: "Asia/Seoul"
  SLACK_WORKFLOW_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"

jobs:
  open-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set release branch postfix
        run: |
          KST_DATE=$(TZ=$TIMEZONE date '+%Y%m%d')
          SEQUENCE_NUMBER=$((GITHUB_RUN_NUMBER))
          echo "RELEASE_BRANCH_POSTFIX=edu-${KST_DATE}-${SEQUENCE_NUMBER}" >> $GITHUB_ENV

      - name: Current release branch
        run: echo "Release branch is release/$RELEASE_BRANCH_POSTFIX"
        
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create branch
        run: git checkout -b release/$RELEASE_BRANCH_POSTFIX develop

      - name: Set git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email chyh1900@gmail.com

      - name: Push release branch
        run: git push -u origin release/$RELEASE_BRANCH_POSTFIX

      - name: Run slack workflow
        run: |
          POST_DATA='{"releaseBranch": "release/'"$RELEASE_BRANCH_POSTFIX"'"}'
          curl -X POST -H 'Content-type: application/json' --data "${POST_DATA}" "$SLACK_WORKFLOW_WEBHOOK_URL"
